#!/bin/bash

#####Set Scheduler Configuration Directives#####

#Name the job:
#$ -N CDNIN

#Send e-mail at beginning/end/suspension of job
#$ -m bes

#E-mail address to send to
#$ -M aekyong-jung@uiowa.edu

#Start script in current working directory
#$ -cwd

#####End Set Scheduler Configuration Directives#####


#####Resource Selection Directives#####

#See the HPC wiki for complete resource information: https://wiki.uiowa.edu/display/hpcdocs/Argon+Cluster
#Select the queue to run in
#$ -q CASMA

#Request four cores
#$ -pe smp 4

#####End Resource Selection Directives#####
apptainer -v exec Templin-Stack-2025-01.sif Rscript drafts/runSimulation.R $SGE_TASK_ID
