#!/bin/bash

#####Set Scheduler Configuration Directives#####

#Name the job:
#$ -N CDNINr

#Start script in current working directory
#$ -cwd

#####End Set Scheduler Configuration Directives#####


#####Resource Selection Directives#####

#See the HPC wiki for complete resource information: https://wiki.uiowa.edu/display/hpcdocs/Argon+Cluster
#Select the queue to run in
#$ -q CASMA

#Request four cores
#$ -pe smp 4

#####End Resource Selection Directives#####
apptainer -v exec /Users/aekjung/Jung_apptainer_202601.sif Rscript drafts/analyzeResults.R $SGE_TASK_ID
